<?php

namespace Api\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * MediaCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaCategoryRepository extends EntityRepository
{
    public function findByActiveNoDeleted()
    {
        $categories = $this->findBy(
            [
                'active' => 1,
                'deleted' => 0,
            ],
            ['sorting' => 'ASC']
        );

        return $categories;
    }
}
