<?php

namespace Api\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends EntityRepository
{
    public function findByActiveModuleFromPath($path)
    {
        $module = $this->findOneBy([
            'active' => 1,
            'deleted' => 0,
            'path' => $path,
        ]);

        return $module;
    }
}
