<?php

namespace Api\Repository;

/**
 * OilCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OilCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
