<?php

namespace Api\Repository;
use Api\Entity\PipelinePropertyValues;
use Doctrine\ORM\EntityRepository;

/**
 * PipelineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PipelineRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findByActiveNoDeleted()
    {
        $pipelines = $this->findBy(
            [
                'active' => 1,
                'deleted' => 0,
            ],
            ['sorting' => 'ASC']
        );

        return $pipelines;
    }

    /**
     * @param int $pipeline_id
     * @return array
     */
    public function findPropertyValuesAnyPipeline($pipeline_id)
    {
        $entityManager = $this->getEntityManager();

        $queryBuilder = $entityManager->createQueryBuilder();

        $queryBuilder->select('v')
            ->from(PipelinePropertyValues::class, 'v')
            ->join('v.pipelineProperty', 'p')
            ->where('v.pipelineId = ?1')
            ->andWhere('p.active = 1')
            ->andWhere('p.deleted = 0')
            ->orderBy('p.sorting', 'ASC')
            ->setParameter('1', $pipeline_id);

        $properties = $queryBuilder->getQuery()->getResult();

        return $properties;
    }
}
