<?php

namespace Api\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * PipelineCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PipelineCategoryRepository extends EntityRepository
{
    public function findByActiveNoDeleted($parentId = 0)
    {
        $categories = $this->findBy(
            [
                'parentId' => $parentId,
                'active' => 1,
                'deleted' => 0,
            ],
            ['sorting' => 'ASC']
        );

        return $categories;
    }
}
