<?php

namespace Api\Repository;
use Api\Entity\PipelineProperty;
use Api\Entity\PipelinePropertyValues;
use Doctrine\ORM\EntityRepository;

/**
 * PipelinePropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PipelinePropertyRepository extends EntityRepository
{


}
