<?php

namespace Api\Repository;
use Api\Entity\Products;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function searchSqlQuery($query)
    {
        $entityManager = $this->getEntityManager();

        $query = str_replace(array('.',',',' ','-','_','/','\\','*','+','&','^','%','#','@','!','(',')','~','<','>',':',';','"',"'","|"), '', $query);

        $rsm = new ResultSetMappingBuilder($entityManager);
        $rsm->addRootEntityFromClassMetadata(Products::class, 'p');

        $nativeQuery = $entityManager->createNativeQuery(
            "SELECT * 
                    FROM products 
                    WHERE MATCH (s_name, sku, name, meta_keywords) AGAINST (? IN BOOLEAN MODE)",
            $rsm);
        $nativeQuery->setParameter(1, "\'+".$query."*\'");

        $results = $nativeQuery->getResult();

        return $results;
    }
}
