<?php
/**
 * This configuration cache file was generated by Zend\ConfigAggregator\ConfigAggregator
 * at 2018-01-12T16:57:32+03:00
 */
return array (
  'dependencies' => 
  array (
    'invokables' => 
    array (
      'App\\Action\\PingAction' => 'App\\Action\\PingAction',
      'Doctrine\\DBAL\\Logging\\DebugStack' => 'Doctrine\\DBAL\\Logging\\DebugStack',
      'Zend\\Expressive\\Helper\\ServerUrlHelper' => 'Zend\\Expressive\\Helper\\ServerUrlHelper',
      'Zend\\Expressive\\Middleware\\ImplicitHeadMiddleware' => 'Zend\\Expressive\\Middleware\\ImplicitHeadMiddleware',
      'Zend\\Expressive\\Middleware\\ImplicitOptionsMiddleware' => 'Zend\\Expressive\\Middleware\\ImplicitOptionsMiddleware',
      'Zend\\Expressive\\Router\\RouterInterface' => 'Zend\\Expressive\\Router\\FastRouteRouter',
    ),
    'factories' => 
    array (
      'Zend\\Router\\Http\\TreeRouteStack' => 'Zend\\Router\\Http\\HttpRouterFactory',
      'Zend\\Router\\RoutePluginManager' => 'Zend\\Router\\RoutePluginManagerFactory',
      'Zend\\Router\\RouteStackInterface' => 'Zend\\Router\\RouterFactory',
      'Zend\\Validator\\ValidatorPluginManager' => 'Zend\\Validator\\ValidatorPluginManagerFactory',
      'App\\Action\\HomePageAction' => 'App\\Action\\HomePageFactory',
      'Zend\\Expressive\\Application' => 'Zend\\Expressive\\Container\\ApplicationFactory',
      'Zend\\Expressive\\Delegate\\NotFoundDelegate' => 'Zend\\Expressive\\Container\\NotFoundDelegateFactory',
      'Doctrine\\ORM\\EntityManager' => 'ContainerInteropDoctrine\\EntityManagerFactory',
      'Zend\\Expressive\\Helper\\ServerUrlMiddleware' => 'Zend\\Expressive\\Helper\\ServerUrlMiddlewareFactory',
      'Zend\\Expressive\\Helper\\UrlHelper' => 'Zend\\Expressive\\Helper\\UrlHelperFactory',
      'Zend\\Expressive\\Helper\\UrlHelperMiddleware' => 'Zend\\Expressive\\Helper\\UrlHelperMiddlewareFactory',
      'Zend\\Stratigility\\Middleware\\ErrorHandler' => 'Zend\\Expressive\\Container\\ErrorHandlerFactory',
      'Zend\\Expressive\\Middleware\\ErrorResponseGenerator' => 'Zend\\Expressive\\Container\\ErrorResponseGeneratorFactory',
      'Zend\\Expressive\\Middleware\\NotFoundHandler' => 'Zend\\Expressive\\Container\\NotFoundHandlerFactory',
      'Twig_Environment' => 'Zend\\Expressive\\Twig\\TwigEnvironmentFactory',
      'Zend\\Expressive\\Template\\TemplateRendererInterface' => 'Zend\\Expressive\\Twig\\TwigRendererFactory',
    ),
    'delegators' => 
    array (
      'Zend\\Expressive\\Application' => 
      array (
        0 => 'Wandfluh\\Factory\\RoutesDelegator',
        1 => 'Media\\Factory\\RoutesDelegator',
        2 => 'Oil\\Factory\\RoutesDelegator',
        3 => 'Pipeline\\Factory\\RoutesDelegator',
        4 => 'Manufacture\\Factory\\RoutesDelegator',
        5 => 'Catalog\\Factory\\RoutesDelegator',
      ),
      'Catalog\\Middleware\\FullPathMiddleware' => 
      array (
        0 => 'Catalog\\Factory\\FullPathMiddlewareFactory',
      ),
    ),
    'aliases' => 
    array (
      'HttpRouter' => 'Zend\\Router\\Http\\TreeRouteStack',
      'router' => 'Zend\\Router\\RouteStackInterface',
      'Router' => 'Zend\\Router\\RouteStackInterface',
      'RoutePluginManager' => 'Zend\\Router\\RoutePluginManager',
      'ValidatorManager' => 'Zend\\Validator\\ValidatorPluginManager',
      'Zend\\Expressive\\Delegate\\DefaultDelegate' => 'Zend\\Expressive\\Delegate\\NotFoundDelegate',
    ),
    'abstract_factories' => 
    array (
      0 => 'Zend\\ServiceManager\\AbstractFactory\\ReflectionBasedAbstractFactory',
    ),
  ),
  'templates' => 
  array (
    'paths' => 
    array (
      'wandfluh' => 
      array (
        0 => 'D:\\OS_Domains\\ah-expressive-public\\src\\Wandfluh\\src/../templates/wandfluh',
      ),
      'media' => 
      array (
        0 => 'D:\\OS_Domains\\ah-expressive-public\\src\\Media\\src/../templates/media',
      ),
      'oil' => 
      array (
        0 => 'D:\\OS_Domains\\ah-expressive-public\\src\\Oil\\src/../templates/oil',
      ),
      'pipeline' => 
      array (
        0 => 'D:\\OS_Domains\\ah-expressive-public\\src\\Pipeline\\src/../templates/pipeline',
      ),
      'manufacture' => 
      array (
        0 => 'D:\\OS_Domains\\ah-expressive-public\\src\\Manufacture\\src/../templates/manufacture',
      ),
      'catalog' => 
      array (
        0 => 'D:\\OS_Domains\\ah-expressive-public\\src\\Catalog\\src/../templates/catalog',
      ),
      'app' => 
      array (
        0 => 'D:\\OS_Domains\\ah-expressive-public\\src\\App\\src/../templates/app',
      ),
      'error' => 
      array (
        0 => 'D:\\OS_Domains\\ah-expressive-public\\src\\App\\src/../templates/error',
      ),
      'layout' => 
      array (
        0 => 'D:\\OS_Domains\\ah-expressive-public\\src\\App\\src/../templates/layout',
      ),
    ),
    'extension' => 'html.twig',
  ),
  'doctrine' => 
  array (
    'driver' => 
    array (
      'orm_default' => 
      array (
        'class' => 'Doctrine\\Common\\Persistence\\Mapping\\Driver\\MappingDriverChain',
        'drivers' => 
        array (
          'Api\\Entity' => 'api_entity',
        ),
      ),
      'api_entity' => 
      array (
        'class' => 'Doctrine\\ORM\\Mapping\\Driver\\AnnotationDriver',
        'cache' => 'array',
        'paths' => 
        array (
          'D:\\OS_Domains\\ah-expressive-public\\src\\Api/src/Api/Entity' => 'D:\\OS_Domains\\ah-expressive-public\\src\\Api/src/Entity',
        ),
      ),
    ),
    'connection' => 
    array (
      'orm_default' => 
      array (
        'params' => 
        array (
          'url' => 'mysql://root@localhost:5890/db1057313_alphahyd',
        ),
        'doctrine_type_mappings' => 
        array (
          'enum' => 'string',
        ),
      ),
    ),
  ),
  'route_manager' => 
  array (
  ),
  'config_cache_path' => 'data/config-cache.php',
  'twig' => 
  array (
    'cache_dir' => 'data/cache/twig',
    'assets_url' => '/',
    'assets_version' => NULL,
    'extensions' => 
    array (
    ),
    'runtime_loaders' => 
    array (
    ),
    'globals' => 
    array (
    ),
  ),
  'config_cache_enabled' => true,
  'debug' => false,
  'zend-expressive' => 
  array (
    'programmatic_pipeline' => true,
    'error_handler' => 
    array (
      'template_404' => 'error::404',
      'template_error' => 'error::error',
    ),
  ),
);
